MODEL: #MODEL field
    framework: "RecognizerDistillation" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    freeze_params_list:
    - False
    - False
    models:
    - Teacher:
        backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
            name: "ResNetTweaksTSM" #Mandatory, The name of backbone.
            pretrained: "data/ResNet50_vd_ssld_v2_pretrained.pdparams" #Optional, pretrained model path.
            depth: 50 #Optional, the depth of backbone architecture.
            num_seg: 8
        head:
            name: "ppTSMHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
            num_classes: 400 #Optional, the number of classes to be classified.
            in_channels: 2048 #input channel of the extracted feature.
            drop_ratio: 0.5 #the ratio of dropout
            std: 0.01 #std value in params initialization
            num_seg: 8
    - Student:
        backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
            name: "PPTSM_v2" #Mandatory, The name of backbone.
            pretrained: "data/PPLCNetV2_base_ssld_pretrained.pdparams" #Optional, pretrained model path.
            num_seg: 8
            class_num: 400
        head:
            name: "MoViNetHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
    loss:
        Train:
            - name: "DistillationCELoss"
              #loss_weight: 1.0  # set loss weight, default 1.0
              model_name_pairs: ["Student", "GroundTruth"]
            - name: "DistillationCELoss"
              model_name_pairs: ["Teacher", "GroundTruth"]
            - name: "DistillationDMLLoss"
              model_name_pairs: ["Student", "Teacher"]
        Val:
            - name: "DistillationCELoss"
              model_name_pairs: ["Student", "GroundTruth"]


DATASET: #DATASET field
    batch_size: 8  #Mandatory, bacth size
    num_workers: 4 #Mandatory, the number of subprocess on each GPU.
    train:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "data/k400/rawframes" #Mandatory, train data root path
        file_path: "data/k400/train.list" #Mandatory, train data index file path
        suffix: 'img_{:05}.jpg'
    valid:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "data/k400/rawframes" #Mandatory, valid data root path
        file_path: "data/k400/val.list" #Mandatory, valid data index file path
        suffix: 'img_{:05}.jpg'
    test:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "data/k400/rawframes" #Mandatory, valid data root path
        file_path: "data/k400/val.list" #Mandatory, valid data index file path
        suffix: 'img_{:05}.jpg'

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 8
            seg_len: 1
            valid_mode: False
        transform: #Mandotary, image transfrom operator
            - Scale:
                short_size: 256
            - MultiScaleCrop:
                target_size: 256
            - RandomCrop:
                target_size: 224
            - RandomFlip:
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
    valid: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 8
            seg_len: 1
            valid_mode: True
        transform:
            - Scale:
                short_size: 256
            - CenterCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
    test:  #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 8
            seg_len: 1
            valid_mode: True
        transform:
            - Scale:
                short_size: 256
            - CenterCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

OPTIMIZER: #OPTIMIZER field
  name: 'Momentum'
  momentum: 0.9
  learning_rate:
    iter_step: True
    name: 'CustomWarmupCosineDecay'
    max_epoch: 120
    warmup_epochs: 10
    warmup_start_lr: 0.0025
    cosine_base_lr: 0.005
  weight_decay:
    name: 'L2'
    value: 1e-4
  use_nesterov: True

MIX:
    name: "Mixup"
    alpha: 0.2


METRIC:
    name: 'CenterCropMetric'

INFERENCE:
    name: 'ppTSM_Inference_helper'
    num_seg: 8
    target_size: 224

model_name: "ppTSMv2"
log_interval: 10 #Optional, the interal of logger, default:10
epochs: 120  #Mandatory, total epoch
log_level: "INFO" #Optional, the logger level. default: "INFO"
